/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paginas;

/**
 *
 * @author gabri
 */
public class HubQuests extends javax.swing.JFrame {

    /**
     * Creates new form QuadroQuests
     */
    public HubQuests() {
        initComponents();
        this.setSize(750, 150);
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelHubopcoes = new javax.swing.JPanel();
        Titulohub = new javax.swing.JLabel();
        btnAdicionarMissao = new javax.swing.JButton();
        btnEditarMissao = new javax.swing.JButton();
        btnRemoverMissao = new javax.swing.JButton();
        btnVerMural = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulohub.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        Titulohub.setText("Escolha da Guilda: Gerenciamento do Mural");

        btnAdicionarMissao.setText("Adicionar Nova Missão");
        btnAdicionarMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMissaoActionPerformed(evt);
            }
        });

        btnEditarMissao.setText("Editar Missão Existente");
        btnEditarMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMissaoActionPerformed(evt);
            }
        });

        btnRemoverMissao.setText("Remover Missão");
        btnRemoverMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMissaoActionPerformed(evt);
            }
        });

        btnVerMural.setText("Ver Mural de Missões");
        btnVerMural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMuralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelHubopcoesLayout = new javax.swing.GroupLayout(PainelHubopcoes);
        PainelHubopcoes.setLayout(PainelHubopcoesLayout);
        PainelHubopcoesLayout.setHorizontalGroup(
            PainelHubopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHubopcoesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAdicionarMissao)
                .addGap(14, 14, 14)
                .addComponent(btnEditarMissao)
                .addGap(18, 18, 18)
                .addComponent(btnRemoverMissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerMural)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelHubopcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulohub, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelHubopcoesLayout.setVerticalGroup(
            PainelHubopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelHubopcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulohub)
                .addGap(18, 18, 18)
                .addGroup(PainelHubopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarMissao)
                    .addComponent(btnEditarMissao)
                    .addComponent(btnRemoverMissao)
                    .addComponent(btnVerMural))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelHubopcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelHubopcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMissaoActionPerformed
        // TODO add your handling code here:
        InsercaoMissao inserir = new InsercaoMissao();
        
        inserir.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnAdicionarMissaoActionPerformed

    private void btnEditarMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMissaoActionPerformed
        // TODO add your handling code here:
        EdicaoMissao editar = new EdicaoMissao();
        
        editar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnEditarMissaoActionPerformed

    private void btnRemoverMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMissaoActionPerformed
        // TODO add your handling code here:
        RemocaoMissao remover = new RemocaoMissao();
        
        remover.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnRemoverMissaoActionPerformed

    private void btnVerMuralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMuralActionPerformed
        // TODO add your handling code here:
        QuadroQuests mural = new QuadroQuests();
        
        mural.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnVerMuralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HubQuests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HubQuests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HubQuests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HubQuests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HubQuests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelHubopcoes;
    private javax.swing.JLabel Titulohub;
    private javax.swing.JButton btnAdicionarMissao;
    private javax.swing.JButton btnEditarMissao;
    private javax.swing.JButton btnRemoverMissao;
    private javax.swing.JButton btnVerMural;
    // End of variables declaration//GEN-END:variables
}
