/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paginas;

import dao.DAOFactory;
import dao.MissaoDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Missao;

/**
 *
 * @author gabri
 */
public class InsercaoMissao extends javax.swing.JFrame {

    /**
     * Creates new form InsercaoMissao
     */
    public InsercaoMissao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaineldeInsercao = new javax.swing.JPanel();
        TituloInsercao = new javax.swing.JLabel();
        btnHub = new javax.swing.JButton();
        lblTituloMissao = new javax.swing.JLabel();
        lbldescricao = new javax.swing.JLabel();
        lblrecompensa = new javax.swing.JLabel();
        lbldificuldade = new javax.swing.JLabel();
        boxdificuldade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescricao = new javax.swing.JTextArea();
        btnSalvarMissoes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txttitulo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtrecompensa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloInsercao.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        TituloInsercao.setText("Chegou até á Inserção de Missões");

        btnHub.setText("Voltar");
        btnHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHubActionPerformed(evt);
            }
        });

        lblTituloMissao.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblTituloMissao.setText("Título da Missão a ser inserida:");

        lbldescricao.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lbldescricao.setText("Descrição da Missão a ser inserida:");

        lblrecompensa.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblrecompensa.setText("Recompensa da Missão a ser inserida:");

        lbldificuldade.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lbldificuldade.setText("Dificuldade da Misão a ser inserida:");

        boxdificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Média", "Difícil", " " }));

        txtdescricao.setColumns(20);
        txtdescricao.setRows(5);
        jScrollPane1.setViewportView(txtdescricao);

        btnSalvarMissoes.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        btnSalvarMissoes.setForeground(new java.awt.Color(0, 255, 102));
        btnSalvarMissoes.setText("Publicar Missão");
        btnSalvarMissoes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 0)));
        btnSalvarMissoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarMissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMissoesActionPerformed(evt);
            }
        });

        txttitulo.setColumns(20);
        txttitulo.setRows(5);
        jScrollPane2.setViewportView(txttitulo);

        txtrecompensa.setColumns(20);
        txtrecompensa.setRows(5);
        jScrollPane3.setViewportView(txtrecompensa);

        javax.swing.GroupLayout PaineldeInsercaoLayout = new javax.swing.GroupLayout(PaineldeInsercao);
        PaineldeInsercao.setLayout(PaineldeInsercaoLayout);
        PaineldeInsercaoLayout.setHorizontalGroup(
            PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeInsercaoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloInsercao)
                    .addGroup(PaineldeInsercaoLayout.createSequentialGroup()
                        .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbldificuldade)
                            .addComponent(btnSalvarMissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(boxdificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHub)))
                    .addComponent(lblTituloMissao)
                    .addComponent(lbldescricao)
                    .addComponent(lblrecompensa))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PaineldeInsercaoLayout.setVerticalGroup(
            PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineldeInsercaoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TituloInsercao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloMissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldescricao))
                .addGap(44, 44, 44)
                .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrecompensa))
                .addGap(34, 34, 34)
                .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(boxdificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldificuldade))
                .addGap(18, 18, 18)
                .addGroup(PaineldeInsercaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvarMissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHub))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaineldeInsercao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaineldeInsercao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubActionPerformed
                                    
       // TODO add your handling code here:
         HubQuests hub = new HubQuests();
        
        hub.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnHubActionPerformed

    private void btnSalvarMissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMissoesActionPerformed
       // 1. Coletar e validar dados (Exemplo simplificado)
    String titulo = txttitulo.getText();
    String descricao = txtdescricao.getText();
    String dificuldade = boxdificuldade.getSelectedItem().toString(); // Assumindo JComboBox

    if (titulo.isEmpty() || descricao.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Título e Descrição são obrigatórios.");
        return;
    }

    // 2. Criar objeto Missao
    Missao novaMissao = new Missao();
    novaMissao.setTitulo(titulo);
    novaMissao.setDescricao(descricao);
    novaMissao.setDificuldade(dificuldade);
    novaMissao.setRecompensa(txtrecompensa.getText());
    novaMissao.setConcluida(false); // Sempre falso ao inserir

    try {
        // 3. Chamar o DAO para persistir
        MissaoDAO dao = DAOFactory.criarMissaoDAO();
        dao.inserir(novaMissao);

        JOptionPane.showMessageDialog(this, "Missão '" + titulo + "' criada e publicada no Mural!");
        
        // 4. Retornar ao Hub (ou limpar a tela)
        HubQuests hub = new HubQuests();
        hub.setVisible(true);
        this.dispose();

    } catch (SQLException | ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Erro de DB: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSalvarMissoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsercaoMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsercaoMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsercaoMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsercaoMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsercaoMissao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaineldeInsercao;
    private javax.swing.JLabel TituloInsercao;
    private javax.swing.JComboBox<String> boxdificuldade;
    private javax.swing.JButton btnHub;
    private javax.swing.JButton btnSalvarMissoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTituloMissao;
    private javax.swing.JLabel lbldescricao;
    private javax.swing.JLabel lbldificuldade;
    private javax.swing.JLabel lblrecompensa;
    private javax.swing.JTextArea txtdescricao;
    private javax.swing.JTextArea txtrecompensa;
    private javax.swing.JTextArea txttitulo;
    // End of variables declaration//GEN-END:variables
}
